server:
  port: 8080
  shutdown: graceful

instance:
  pid: orchestration-api

logging:
  file:
    path: logs
  level:
    root: info
    web: info
    com:
      bithumbcorp: debug
  logback:
    rollingpolicy:
      max-file-size: 500MB
      clean-history-on-start: false

spring:
  application:
    name: ${instance.pid}
  cloud:
    config:
      name: ${instance.pid}
      profile: local
      default-filters:
        - name: Global
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: login
          uri: http://localhost:8082
          predicates:
            - Path=/orch/login
          filters:
            - RewritePath=/orch/(?<path>.*), /orch
            - name: OrchSync
              args:
                httpMethod: GET
                url: http://localhost:8081/member/block
                save: false
            - name: OrchSync
              args:
                httpMethod: GET
                url: http://localhost:8081/member/id
                save: false
            - name: OrchSync
              args:
                httpMethod: GET
                url: http://localhost:8081/member/password
                save: false
            - name: OrchSync
              args:
                httpMethod: GET
                url: http://localhost:8081/member/sfa-type
                save: true
            - name: CustomModifyRequestBody
            - name: CircuitBreaker
              args:
                name: memberDetailInfoServiceCircuitBreaker
                fallbackUri: forward:/serviceFallback
                preLogger: true
                postLogger: true
        - id: myAsset
          uri: http://localhost:8082
          predicates:
            - Path=/orch/my/asset
          filters:
            - RewritePath=/orch/(?<path>.*), /orch
            - name: OrchAsync
              args:
                list: GET http://localhost:8081/member/info Y,GET http://localhost:8081/asset/info Y,GET http://localhost:8081/tradeinfo Y
            - name: CustomModifyRequestBody
        - id: memberInfo
          uri: http://localhost:8081
          predicates:
            - Path=/member/**
          filters:
            - name: CircuitBreaker
              args:
                name: memberDetailInfoServiceCircuitBreaker
                fallbackUri: forward:/serviceFallback

      # TODO 리소스 서버 추가 필요

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 60
        sliding-window-size: 60
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000 # circuitbreaker OPEN
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8787/eureka